### ISSUE TITLE
Problem when using --rendertiddlers

### ISSUE THREAD

**Issue by wwc559** [kixam/TW5-datePicker#12]
Whenever I have a tiddler with <$edit-date> in it, it causes tiddlywiki --rendertidlers to die with this error message.

% tiddlywiki --rendertiddlers [!is[system]]  $:/core/templates/static.tiddler.html static text/plain
/usr/local/lib/node_modules/tiddlywiki/boot/boot.js:101
	var doc = options.document || document;
	                              ^

ReferenceError: document is not defined
    at $tw.utils.domMaker (/usr/local/lib/node_modules/tiddlywiki/boot/boot.js:101:32)
    at Widget.DatePickerWidget.render ($:/plugins/kixam/datepicker/widget.datepicker.js:51:29)
    at $:/core/modules/widgets/widget.js:373:15
    at $tw.utils.each (/usr/local/lib/node_modules/tiddlywiki/boot/boot.js:69:12)
    at Widget.renderChildren ($:/core/modules/widgets/widget.js:372:12)
    at Widget.ListItemWidget.render ($:/core/modules/widgets/list.js:299:7)
    at $:/core/modules/widgets/widget.js:373:15
    at $tw.utils.each (/usr/local/lib/node_modules/tiddlywiki/boot/boot.js:69:12)
    at Widget.renderChildren ($:/core/modules/widgets/widget.js:372:12)
    at Widget.ListWidget.render ($:/core/modules/widgets/list.js:43:7)

**Comment by kixam** [comment]
hello @wwc559 

`document` is not defined in node.js, nor is `window`. These are only defined in browser (compiled) mode of TiddlyWiki. I do not know how you ended up executing this line in `boot.js` tiddler (which is a core file of TiddlyWiki's, not provided by the plugin), my guess would be that you are missing some option in your command line ? Sorry, I do not use TW5 with node.js and thus I am not familiar with all the technical details on how it works. What version of TW5 and what plugins are you using ? I could try to reproduce your case and hopefully give you further advice

**Comment by wwc559** [comment]
Agreed.  I think I have the right options as it works well if I don't have <$edit-date> in any tiddlers.

Since I'm not familiar with the technical details of TW5/node.js or your code (and your code is minified so it is difficult to look at), I don't know how to proceed here.  If you could reproduce it would certainly be good to know :)

Thanks for your help!

**Comment by wwc559** [comment]
Hi,

I've done a bit more investigation.  It is a bit hard as I only have the minified version of your widget, but looks like you call domMaker in .render() to cause the editor widget to popup.  I think what needs to be done is detect when parent is not in the browser context (maybe document undefined?)  and just render the current date in the input field (or something like that).  I don't really know how you do that, but in looking at the TiddlyWiki source files, almost none of them use domMaker (really only stuff in boot.js).  So I don't know how other widgets take care of this problem, it appears none of the core/modules/widget/* calls domMaker().  So I don't know how they handle the situation.

Thanks again for your help, hope this note is helpful to you!

**Comment by jasonmhoule** [comment]
This may be a relatively simple fix, see this Google Group: https://groups.google.com/g/tiddlywiki/c/pjqXOaHGw1w/m/4zgb2NVxAQAJ

I came to this by way of the issue linked by @sobjornstad. In addition to datepicker (which I have to disable when I sync to TiddlyRemember), I had a small JS tiddler that was also causing the issue. I already had it setup using the declarations that Sycom mentions in this thread; adding the suggested `exports.after = ["rootwidget"];` made the difference and that script no longer causes issues with TiddlyRemember sync, which uses `--render`.

**Comment by jasonmhoule** [comment]
It seems that my suggestion above is not bulletproof and also would not work for widget modules.

Another workaround I am playing with is to add `if (!$tw.browser) { return; }` as the first line under a widget's `.render` method (and also in a few other spots that have caused trouble with TiddlyRemember sync). I only use a browser TW so I'm not sure if this would screw up a wiki running on node (I suspect it might), but it gets the job done for my TiddlyRemember workflow.
